name: Products
description: 'Comprises all the product stuff which will be set on a marketplace module.'
type: module
core: 8.x
dependencies:
  - field
  - file
  - image
  - menu_ui
  - node
  - path
  - text
  - user
  - views
version: 8.x-1.0
package: Marketplace
core_incompatible: false
