products_cookies:
  version: VERSION
  dependencies:
    - core/drupal
    - core/jquery
    - core/jquery.once
  js:
    vendor/js-cookie/js-cookie/src/js.cookie.js: {}
    js/products.js: {}
  css:
    theme:
      css/products.css: {}
products_block_styles:
  version: VERSION
  css:
    theme:
      css/products_block_styles.css: {}
