<?php

/**
 * @file
 * Contains products.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function products_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the products module.
    case 'help.page.productos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Módulo para gestión de productos') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function products_theme() {
  $path = drupal_get_path('module', 'products') . '/img/icon/cart.png';
  return [
    'products' => [
      'render element' => 'children',
    ],
    'cart_block' => [
      'variables' => [
        'img' => [
          'class' => "img-checkout-block",
          'src' => $path,
          'alt' => 'Shopping cart',
          'height' => '40px',
          'width' => '40px',
        ],
        'button' => [
          'class' => "button buton-action button--primary button--small button-hidden",
          'text' => 'Proceed to checkout',
          'href' => 'products/cart',
        ],
      ],
      'render element' => 'children',
    ],
  ];
}

function products_preprocess_page(&$variables) {
  $variables['page']['#cache']['contexts'][] = 'route';
  $route = [
    "view.product_products.page_products",
    "view.product_products.page_product_unitary",
  ];
  if (in_array(\Drupal::routeMatch()->getRouteName(), $route)) {
    $variables['#attached']['library'][] = 'products/products_cookies';
  }
}
